### ISSUE TITLE
Prompt for location when "failed to locate main schema resource"

### ISSUE THREAD

**Issue by pryrt** [morbac/xmltools#11]
While helping people in the NPP Forums, I've seen a couple of recent questions about the find-XSD-location popup not appearing when expected.
1. https://notepad-plus-plus.org/community/topic/16274/need-to-load-xsd/2
The first case seemed reasonable to me: it doesn't prompt when the XSD is referenced in the XML, and the XSD file was properly found.  

2. https://notepad-plus-plus.org/community/topic/16359/validate-now-not-able-to-validate-xml-against-schema
In the second, I think a feature could be added: if there is an XSD specified using `xsi:noNamespaceSchemaLocation` in the XML, but that referenced XSD file cannot be found, I think the popup should appear asking for the location, rather than just giving an error that it "failed to locate main schema resource"

**Comment by iuriemaxim** [comment]
Actually the XML is considered Valid if the so called ”main schema” is the last one in the xsi:schemaLocation enumeration. For example if the first element is <wfs:.......>, then Notepad++ will consider hat the main schema is http://www.opengis.net/wfs/2.0 as xmlns:wfs="http://www.opengis.net/wfs/2.0".

Notepad++ will consider the file being valid either:
1) if the _xsi:schemaLocation="http://www.opengis.net/wfs/2.0"_ 
2) or if the xsi:schemaLocation has http://www.opengis.net/wfs/2.0 at the end of the list, such as for example _xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ef/4.0 http://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd http://www.opengis.net/wfs/2.0"_.

This is quite sure odd and incorrect because:
1) the location of the xsd schema for wfs was not supplied in the schema location list, as correct would be to provide the link to the xsd schema as well, such as for example: _http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd_
2) there is no requirement to provide the location of the xsd schemas in a certain order, for example having the location of the wfs schema first or last. Both _xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ef/4.0 http://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd"_ and _xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://inspire.ec.europa.eu/schemas/ef/4.0 http://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd"_ are correct and the XML file should be valid if it validates against both XSD schemas and by those schemas that are imported by these two schemas.

Therefore, as currently implemented, Notepad++ can't be used to correctly validate an XML file.

**Comment by mostafa901** [comment]
any luck with one, facing same issue too

**Comment by morbac** [comment]
Hi,
Please can you just tell which version you're using ?
Is this better with xmltools 3 (MSXML-based) ?

**Comment by iuriemaxim** [comment]
Hi,

This is the version used for the XML Tools Plugin.

![image](https://user-images.githubusercontent.com/20813598/75135109-28cb4400-56e9-11ea-95e9-f8bbeb72e569.png)

**Comment by morbac** [comment]
Actually the sourceforge repo is outdated.
Please check for updates on the current github project.
Latest release is here: https://github.com/morbac/xmltools/releases/tag/3.0.3.2

**Comment by iuriemaxim** [comment]
Hi,

This was the error message in XML Tools version 2.4.9.2 (October 2016) 

![image](https://user-images.githubusercontent.com/20813598/75136256-c411e880-56ec-11ea-860e-517c08963da1.png)

And this is the actual message in XML Tools version 3.0.3.2 (February 2020)

![image](https://user-images.githubusercontent.com/20813598/75137062-43082080-56ef-11ea-8d29-d703b9d9186e.png)

Well done morbac!

**Comment by iuriemaxim** [comment]
For another file, XML Tools version 2.4.9.2 provides the following error message if the last XSD schema in the xsi:schemaLocation element is not wfs.xsd

![image](https://user-images.githubusercontent.com/20813598/75138729-97ad9a80-56f3-11ea-9d34-00ad100eff6e.png)

and no error is triggered in XML Tools version 2.4.9.2 if the last XSD schema in the xsi:schemaLocation element is wfs.xsd.
![image](https://user-images.githubusercontent.com/20813598/75139101-7bf6c400-56f4-11ea-9391-c6454407d1f8.png)




No error is triggered by XML Tools version 3.0.3.2 as it does not depends the order of the XSD schemas in the xsi:schemaLocation element.

![image](https://user-images.githubusercontent.com/20813598/75138919-0c80d480-56f4-11ea-8601-c0ca1ea34223.png)

**Comment by iuriemaxim** [comment]
I think that this issue can be closed now.
