### ISSUE TITLE
Pretty print no longer formats files correctly

### ISSUE THREAD

**Issue by Chase817** [morbac/xmltools#151]
I have updated XMLTools for the first time in a long time and am finding that all of the recent builds that are compatible with Notepad++ 8.3.2 (namely XMLTools 3.1.1.12) do not format files the way they used to when using pretty print.

Take this example string: `<trust:RequestSecurityTokenResponseCollection+xmlns:trust="http: docs.oasis-open.org ws-sx ws-trust 200512"><trust:RequestSecurityTokenResponse><trust:RequestedSecurityToken><Assertion+ID="SamlSecurityToken-abf4cbb3-5d75-43d4-99c1-0aa7ef5e7a59" +IssueInstant="2022-03-23T15:51:35.842Z" +Version="2.0" +xmlns="urn:oasis:names:tc:SAML:2.0:assertion">`

Try pretty printing it in the most recent XMLTools. For me, this will result in no change in formatting, it will just stay as a single line. In an older version of XMLTools (2.4.11.0), this would result in an output of 4 lines, each with a tab indent greater than the last.

This may be due to the "+" characters, which are added by the browser that intercepted this file and can be decoded to spaces. But still, the old plugin was not bothered by this.

This is a big issue for me as I am inspecting large XML files often and pretty print is now much less useful than it used to be.

**Comment by morbac** [comment]
I'm surpised that previous version was able to pretty print your example. Actually previous version is implemented as "StringXml" formating engine (available in xmltools options dialog). I tried formating your example with StringXml and it entered in a infinite loop, caused by the unexpected invalid structure of your example.

I'll fix that infinite loop but cannot do more actually : your example has many invalid elements and pretty print is not able to guess structure. The best advice I can give is to use the NPP find/replace dialog and replace all "+" chars by space before invoking the pretty print. Another option is to simply replace all "><" sequences with ">\n<".
