### ISSUE TITLE
When trying to save a new XSLT (Save As...) in Notepad++, the App goes to "not responding"

### ISSUE THREAD

**Issue by lucky1luc** [morbac/xmltools#154]
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.556
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppHorizontalRuler.dll SQLinFormNpp64.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/33922423/160641861-19f2353e-389d-457f-86fd-543f51310d1c.png)

The XSLT is +/-49000 lines big. 
I reproduce this by
- I create an XSLT with Mapforce
- Paste the XSLT in a new document in notepad++
- Do file, Save As, select a folder, enter a filename and click OK
- Notepad becomes unresponsive.

Remarks:
- When I kill the process, and restart Notepad (the XSLT is temp saved, so is still in Notepad++ and press save as, it saves within a couple of seconds.
**- When I remove the XML-tools plugin, the saving is (almost) instanteneous.
- When I reinstall the XML-Tools (from the plugin-admin) the behaviour returns.**
- Notepad++ (Not responding is top CPU user:
![image](https://user-images.githubusercontent.com/33922423/160643661-0344e033-7468-4b2a-8c68-abf3ec89b059.png)
It indicates that Notepad++ is doing something in Memory which is taking a lot of effort (and after one hour of this, notepad is still not responding.

**Comment by morbac** [comment]
@lucky1luc, @vinsworldcom, a new pre-release was built to fix issue #152
I suspect that both issues have same cause : an internal conversion UTF-8 to UCS2 (required by MSSQL) was not optimized and very slow on big files. This conversion is perfomed on XML syntax check. Therefore if you have the "Enable XML syntax auto-check" option enabled, the XML syntax check is performed automatically on every Save.

The new pre-release 3.1.1.13 is available on following url: [https://drive.infomaniak.com/app/share/475371/df8e7a5e-8195-4141-b363-2db03645bba2](https://drive.infomaniak.com/app/share/475371/df8e7a5e-8195-4141-b363-2db03645bba2)

Regards

**Comment by lucky1luc** [comment]
Thank you, I will first attempt to switch off the "Enable XML syntax auto-check" before trying to install software which is not on GitHub. With all due respect, I do not want to download a file from an unknown source. That is an unacceptable risk for me. Then I rather wait until the official version comes out, and it can be installed from the official site.

**Comment by mimccu** [comment]
I disabled the "Enable XML syntax auto-check" and I was able to save a 2 MB XML file quickly.  However, when using "Evaluate XPath Expression" it still failed (hour glassed).  I'm assuming it did a XML syntax check at that point.  Any word on when a regular release is coming and not a pre-release?

**Comment by mimccu** [comment]
Also, what is the most recent prior version of the plugin that did not have this issue?  I can work with that in the meantime?

**Comment by vinsworldcom** [comment]
@mimccu I think [8.2.1](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.2.1)

**Comment by morbac** [comment]
> Any word on when a regular release is coming and not a pre-release?

I plan to build a new release during incoming weekend.

**Comment by mimccu** [comment]
My colleague is on Notepad++ 8.2.1 and she does not have issues.  However, I went back to version 8.2.1 and still have issues, so I'm not entirely sure it's due to the Scintilla API changes in more recent versions of Notepad++.

My plugin version is:
![image](https://user-images.githubusercontent.com/34164941/161155272-be636e61-ce83-4d40-a20e-4605846df05d.png)

**Comment by Gitoffthelawn** [comment]
What's the easiest way to check which version of Scintilla your current version of Notepad++ is using?

**Comment by rdipardo** [comment]
@Gitoffthelawn,
> What's the easiest way to check which version of Scintilla your current version of Notepad++ is using?

The only place to find that is the `version.txt` file in [the git repository][0].

But the above discussion has nothing to do with the version of Scintilla. All Notepad++ versions [from 7.9.4][1] to now have used Scintilla 4.4.6.

What _did_ change after version 8.2.1 is [the size of an important data structure][2] that plugins like XMLTools depend on. 
Notepad++ made this change independently of Scintilla, in order to support files sizes of >2 GB.

Funny thing is, Scintilla has provided this ability for [a long time][4]. The [announcement of Scintilla 4.1.6][3] reads in part:

> The major feature of this release is support for files larger than 2 gigabytes in SciTE

("SciTE" being [the original Scintilla-based text editor][5].)

So, Notepad++ committed itself to an API that is _not only_ incompatible with all plugins that worked in 8.2.1 &#x2014; it's not even compatible with the current Scintilla!


[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/version.txt
[1]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d7819cf601051510b7fa1640ca17fedad297e1f8
[2]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11198
[3]: https://groups.google.com/g/scintilla-interest/c/4czxAqELLeQ/m/2XzoM5gsBwAJ
[4]: https://sourceforge.net/p/scintilla/code/ci/rel-4-0-0/tree/include/Sci_Position.h#l15
[5]: https://en.wikipedia.org/wiki/SciTE

**Comment by mimccu** [comment]
Thanks @rdipardo.  Maybe we should petition Notepad++ to reverse course and use the large file size capabilities that are inherent to Scintilla instead of going outside Scintilla to support large file sizes?  (I'm hoping I interpreted what you said correctly).

**Comment by morbac** [comment]
[New release 3.1.1.13](https://github.com/morbac/xmltools/releases/tag/3.1.1.13) should fix the issue

**Comment by mimccu** [comment]
Thanks very much @morbac -- I used release 3.1.1.13 with Notepad++ 8.3.3 64 bit version for Windows and both saving a XML file and evaluating XPath expressions are working now.  Note that using the Plugin Admins tool under Notepad++ does not see XML Tools version 3.1.1.13 yet -- it only sees the prior version available for download.

**Comment by mimccu** [comment]
On a separate note, can you tell me if this is a known issue under XML Tools?  I have a FHIR Bundle that declares a default namespace at the top level.  If I use evaluate XPath expression with the default namespace, it does not find any entries that match.  However, if I remove the default namespace, evaluate XPath expression works.  I tried to declare a default namespace under evaluate XPath expression but that didn't produce any better results.
Here's an example:
- XPath expression: /Bundle/entry/resource/Organization/id/@value
- Example files with working (default namespace removed) and non-working (default namespace in use) example:
[CeQ_inactive_entries_simple_examples.zip](https://github.com/morbac/xmltools/files/8410172/CeQ_inactive_entries_simple_examples.zip)
 
Thanks,
Mike

**Comment by 537mfb** [comment]
Can confirm version 3.1.1.13 fixes the not responding issue

**Comment by morbac** [comment]
> Note that using the Plugin Admins tool under Notepad++ does not see XML Tools version 3.1.1.13 yet -- it only sees the prior version available for download.

A [pull request](https://github.com/notepad-plus-plus/nppPluginList/pull/434) has been sent and merged in NPP plugin a few days ago. Therefore plugin admin will show version 3.1.1.13 when next NPP version will be released.
