### ISSUE TITLE
Pretty print is slow (linearalized xml 10MB)

### ISSUE THREAD

**Issue by LetMeSleepAlready** [morbac/xmltools#55]
It takes more than a minute to pretty print an xml file that is provided in linearalized form. For a linear process that does string operations, 10MB is not much to process. It is not like it is doing DOM operations or something like that.

Looking at the pretty print function it does 2 passes. First it cleans it up, then it pretty prints them. Both passes mutate a std::string object which isn't efficient, and the longer the input string is, the slower everything will become.

If we were to use an std::stringstream to always create a copy instead of mutating the input string all the time, then these two passes could be combined into a single operation. I believe this could boost prettyprint performance significantly on longer inputs.

**Comment by NonInspirationalName** [comment]
I have made a replacement for the pretty print functionality. It also handles the linearize functionality. For my 10MB file, the processing time for pretty print went from 8 minutes to 400ms, and for linearize from 7 minutes to 200ms.

I have kept the original, and simply added mine next to it.
![image](https://user-images.githubusercontent.com/35378209/90989665-d38ac500-e59b-11ea-9772-20a918531b6f.png)


I noticed a few strange behaviours on the original implementation, so I tried to fix these as well... which I think I did... but can't be too sure since I have a limited test set.

At least the following file pretty prints correctly (even though it's not valid XML):

```
<?xml version="1.0"?>
<hello>
	<This attr1="fo>o " attr2="sad<fa>/fa>sdf " isattributenovalue />
	Great balls of fire
	<foo/>
	whoooaaaaa yeah some enter tab tab tab
</hello>
fdgdgf

```
The original code made the following out of it:
```
<?xml version="1.0"?>
<hello>
	<This attr1="fo>o " attr2="sad<fa>/fa>sdf " isattributenovalue />Great balls of fire<foo/>whoooaaaaa yeah some enter tab tab tab</hello>fdgdgf
```


However.....
After that I went gung-hu on the source code and cleaned it (VC++ warning level 4) and split functionality from XMLTools.cpp to various sub-files for each respective tool (validation, text convert, pretty print etc) to make it better manageable. The original file was over 2500 lines.. its now 360

Changes: 
1.  Added debug levels, so that even in release mode you can see debugging information (if you want). Previous debugs were set to 'TRACE' level, and default setting for showing is 'INFO'.. so not much is output by default
2. Rewrote config reading/writing. Put it in a separate class and its no longer spread out all over the place
3. Changed settings toggle code (code-reuse)
4. Moved code to separate files (bundling functionality, separation of concern, etc).
5. Explicitly did NOT change any of the existing tool -functionality- and -code-, just moved it around. So functions should work as before. Most of the work was in code splitting and NPP/SCI/app related code.
6. Removed unused variables and declarations.
7. Changed the menu creation (no longer bound to config reading) and updating of values. (Also in separate file)
8. Added timing info to both existing pretty print and new pretty print in the debug window (level: info) 

So now I am not quite sure on how to proceed :) It would probably be the easiest if you would simply accept the whole thing, as I am confident that it will improve the code quality a lot, and will make collaboration easier.. but it is your project and not mine so don't know...

Possibly related:
[https://github.com/morbac/xmltools/issues/36] closing empty elements
[https://github.com/morbac/xmltools/issues/34] closing element missing (all comments in issue solved)
```
<abschlusskonto>
	<pruefungen>
		<pruefung>
			<extId>CASE233057_TEST1_AA.8873.10.20182</extId>
			<examinationAttributes/>
		</pruefung>
	</pruefungen>
	<zusatzpruefungen/>
</abschlusskonto>
```


[https://github.com/morbac/xmltools/issues/51] removing new lines (I explicitly did not solve this, as it breaks pretty print's principles
[https://github.com/morbac/xmltools/issues/44] non-roman digits... it seem to work fine

**Comment by morbac** [comment]
Hi,

Thank you for your great job. I have not longer much time to dedicate to the plugin and I very appreciate when someone spend time and efforts for helping.
I shortly gave a look at your fork and for what I saw, I confess that your code is much cleaner and well-organized than mine. I also agree with you in the way that my actual prettyprint is slow.

I'll study in details your modifications and apply them in my project as soon as possible.
Thanks a lot

**Comment by NonInspirationalName** [comment]
Hi,

In the mean time I had already refactored my own code (For the fast pretty print part) even more. It is limited to the 'toolsPrettyPrintFast.cpp' file. Basically separating the lexer and the parser. I'll clean that up and push it later. 

If you want I can merge your latest changes in my fork, if that helps in getting things going. Just let me know if I can help with anything... 

Thanks

**Comment by NonInspirationalName** [comment]
Merge is done, and I created a clean mergeable pull request (draft). This makes it easier to find changes (although this is hard anyway because of the movement to new files..) and a lot easier to merge it (since it can be done automatically after review)

Please let me know if you want something changed there.

**Comment by morbac** [comment]
I just reviewed the unit tests and I think that `Test1.out.xml` is wrong. Let's try a easier example. The prettyprint fast function converts
```
<p>hello<b>world</b>!</p>
```
into
```
<p>hello
  <b>world</b>
  !
</p>
```
I think this is wrong. The pretty printed version should be the same as original:
```
<p>hello<b>world</b>!</p>
```
Btw, this is exactly the output of prettyprint when I test with altova xmlspy.

In my undestanding of xml, whitespaces (and line breaks) are unsignificant only between attributes or tags. Therefore, pretty print can only add whitespaces (and line breaks) in these locations, but not before, after or in the middle of a text node, or betwee a text node and an element node.

As a demonstration, we can try to transform the xml using following xsl stylesheet:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="text()"><xsl:value-of select="string-length(.)"/>+</xsl:template>
</xsl:stylesheet>
```
This simply prints the text nodes length separated with a plus. With the original not-prettyprinted xml, this outputs `5+5+1+`. 
If I apply the xsl to wrong-prettyprinted xml, this produces `7+5+4+` when using TAB for indentation and `8+5+5+` when using 2-spaces for indentation.

Transformation result is not the same for original and prettyprinted versions. In my opinion, this shouldn't happend and prettyprint shouldn't change the xml logical structure, unless the user should be aware of that.

The original slow prettyprint function was designed to not change the logical structure and I'll try to apply this on fast version too. Maybe it would be more elegant to let the user choose the type of prettyprint he wants to use, either via an option or via a well-labeled prettyprint function.

**Comment by NonInspirationalName** [comment]
I think your are right. 

For me the text/element/text/closeelement/text was more experimenting and less adhering to standards. "It looked nice in my example" is the best reason i can give.

As a side note, text and whitespace between tags are always significant if no schema has been attached, so how could we ever insert newlines to pretty-print from a linearized form? Here we already make our own decision on what we allow and what not. 

I guess we need to "formalize" what we expect from it a bit first. Luckily the unit tests offer a great "documentation" for this. 

For example, currently the fpp strips away pre/postfix spacing from TEXT. We could make this an option. 

Your thoughts?

**Comment by NonInspirationalName** [comment]
Thanks for the upload. Its insightful.

Personally I am fine with just having a strict version and not bother with my experiment. My reasoning:

* Ensures compatibility with the existing prettyprint function in previous releases
* Faster progress to a new release.
* Less/Simpler unit tests
* So far I never had to work (or plan to work) with 'unstructured' xml that can not be directly translated to a programming class/struct format. So for me strict would already fit all my requirements anyway, so there is no incentive.
* We can add variations on 'strict' in the options as long as this does not completely undermine strict workflow

Options that I would prefer (could already exist):
* Auto close tag
* Trim TEXT whitespace `( "   this is a text   " => "this is a text" )`

Going back to the strict rules: I think I can summarize the line break handling in your unit test as follows

**Allow adding a new line between `<tag1>` and `<tag2>` if and only if there is no TEXT in between that is not xml-whitespace
In all other cases, disallow. **

In your example i see that you also do not 'line break' CDATA. So for the above abstract we can simply assume that CDATA follows TEXT rules.

Am I going in the right direction with this?

**Comment by morbac** [comment]
Yeah absolutely ! 😄👍

I'm ok with the idea of having only a strict version. Ok too with the idea of options "Auto-close tag" and "Trim text whitespace", but we need to prepare a unit test for this last option. For instance in the xml `<p> this is <b>bold</b></p>`, the only trimmable whitespace is the one before `this`. The whitespace after `is` shouldn't be trimmed imho. So we can summary with following rule for text trim:

**Then, only the first text-child of a node can be left-trimmed and the only last text-child of a node can be right-trimmed.**

I agree with the summary about line break addition, keeping in mind that CDATA behave like TEXT. This means that 
```
<tag>     <![CDATA[     x     ]]>     </tag>
```
will output
```
<tag><![CDATA[     x     ]]></tag>
```
when "Trim text whitespace" is enabled, and
```
<tag>     <![CDATA[     x     ]]>     </tag>
```
when "Trim text whitespace" is disabled. The content of CDATA block keeps always untouched.

**Comment by NonInspirationalName** [comment]
I see where you are going to with the whitespace. My only use-case would be the simple case <tag> some text </tag>, and not all other variants.  However i can see it would break the not-so-simple use case and thus requires more work than just looking at each TEXT individually **if** we want to be white-spacing 'perfect'. For me it is not an important feature at all, so lets just make 'trim whitespace' a separate issue/feature request for now and we can discuss it later.

See issue #68

**Comment by NonInspirationalName** [comment]
Concerning whitespace:
[https://www.w3.org/TR/xml11/#sec-white-space](url)

Here basically it states that it is up to the application consuming the xml to figure out what to do with whitespace EXCEPT when a DTD is attached with an ATTLIST for the element declaring xml:space/preserve.

It would require tracking the full element stack to implement this, as well as reading the DTD (possibly external, or with a full schema). It will also be more error-prone (how can we recover from errors from incorrect XML? we can not ). 

Either way we're doing a 'best effort' as it is, so for now the above changes seem 'far away, if ever'.

For me the clearest goal would be that linearize and pretty print are their exact opposites.. that is, I can linearize and prettyprint and linearize many many times in sequence and I still get the same result. This is currently not the case, as the original linearize already removed -all- newlines (effectively, trimming all whitespace).

**Comment by morbac** [comment]
Hi, I couldn't work on the plugin during this week-end, I was out of my home. I've seen you did lot of work and I'll discover all of that tonight.

It's true that pretty print and linearize are "best effort" functions, and it's a good thing if they work on invalid xml. Therefore w3c rules don't really apply in our case. Moreover, we do not "consume" xml, but just update its structure.
They shouldn't break xml structure (note that the old linearize function does not guaranties it), especially on valid-structured xml.

**Comment by LetMeSleepAlready** [comment]
Problem is solved not with one but 2 new pretty printers. Saves me already minutes a day!
