### ISSUE TITLE
SimpleXml lib

### ISSUE THREAD

**Issue by NonInspirationalName** [morbac/xmltools#72]
I separated the simplexml+prettyprint library to a separate .lib project. This makes it better re-useable and gives me focus while working on it. it also makes compiles faster.

I am more and more working on the backend library of the 'SimpleXml' namespace. Total revamp must be over 80% of the code base.
I have made a syntax validator that solves problem #45 by reducing the footprint to almost 0 (when working on large files). Effectively, I not only made the output streaming, but also the input... if you had looked at the old code you would know how much changes were needed :) It also makes the footprint for pretty-print smaller, supports DTD and also is able to read the DTD and a DOM (for DTD validations and possibly schemas later on)

I did however not commit any changes yet as the xmltools repo is GPL-3 and that would mean certain things for the code. GPL-3 is a very copy-left license which is only non-restrictive to open-source projects, but hates everything else. To be honest I don't much like GPL-3. 

I am _considering_ moving the SimpleXml namespace into a separate repo, under a different license (GPL-3 compatible so consumable by xmltools). I am however still researching how debugging would go then with the combo, and how versioning and releases, possibly a nuget package would work...  and really it is stuff I would rather not think about at all. I prefer coding... The good part about it is however that we would get separate versioning so that breaking changes can be made easier, and when there are problems xmltools could 'drop a version' to temporary resolve newly introduced bugs. 

I would like your input on this. 

PS: difference in memory consumption on a 200MB xml file

MSXML6
![2020-09-17 200MB MSXML6](https://user-images.githubusercontent.com/35378209/93501988-6fe38580-f916-11ea-9195-d6b7bef3909b.PNG)

SimpleXml DOM
![2020-09-17 200MB SimpleXml DOM](https://user-images.githubusercontent.com/35378209/93502008-7671fd00-f916-11ea-88b9-da09ead0b6be.PNG)

SimpleXml Streaming
![2020-09-17 200MB SimpleXml Low Mem](https://user-images.githubusercontent.com/35378209/93502042-7d990b00-f916-11ea-8c88-b962cc573519.PNG)

**Comment by morbac** [comment]
Well, I appreciate the efforts you invest in improving xmltools. I also understand the logic behind putting the pretty-print functions into an external lib especially if you plan to reuse it in other projects. I think this could be a valid solution as long as the SimpleXml would be available as a LIB, and not only as a DLL. I partially dropped libXML because it forced to have DLL dependencies.
Moreover, I've always less and less time to devote to xmltool and relying on a reliable and fast lib would be a good thing for me.

The not-so-good thing would be about customization. The issue #71 is a good example : it would be more complex for me to improve the plugin with such feature if the SimpleXml is separate. But maybe it would be possible via pull request on the SimpleXml project.

Maybe the best solution is "try and see". Let's try the SimpleXml lib as a separate lib and see how it evolves...

A final note about GPL-3 license : I'm not married to GPL-3 (my wife's name is Sarah, lol). Almost one month ago, the xmltools was absolutely free of any license, and no new version has been officially released under the GPL-3 model. I'm open to proposition about other license models.

**Comment by NonInspirationalName** [comment]
I read up one some of the licensing stuff, and more so copyright. I have decided that really it is a rabbit hole I don't want to get into. Too much legal, not enough play.

In short, yes we have copyright to our code, which means that we can stick whatever license we want to put on it (even multiple!)

BUT if we accept (and we will) PR request from others then any change would require written permission of all contributors (or remove that code.. which ones??) and possibly legally-approved transfer of copy right which is different in different places. 

So ya, but nah.

So in short, its not fun. I believe the MIT license is more fitting. At least it states that 'yeah whatever, do what you want' as opposed to the GPL-3 which states 'yeah whatever as long as you are also GPL-3'.

If you can change the license to MIT then at least we can use our own stuff for whatever as well... if we were so to desire. I will then just keep working on this repo, and it makes everything so much easier. We would need to add a small 'waiver' that whatever PR comes in, automatically will also get MIT. I think the node.js repo has a nice short version [(https://github.com/nodejs/node/blob/master/CONTRIBUTING.md) ] we could .. 'borrow'.

PS: Sarah is a much better name for a wife than "GeePee'el'three"

**Comment by NonInspirationalName** [comment]
I just considered a downside: Moving the whole project to MIT will block us from using GPL-3 dependencies if we were to ever need that. This might not be handy in the long term for xml-tools itself.

**Comment by NonInspirationalName** [comment]
To avoid complexity I will just push all code under gpl3. Its better for the xmltools plugin itself. Expect an update later this weekend after I clean up some stuff. 

"They" won... I guess. I'll just hope copyright holds up *just in case it is needed* and add a header to each file. You're welcome to add your name there as well.
