### ISSUE TITLE
After using Notepad++ for a while, a single undo reverts many changes

### ISSUE THREAD

**Issue by rkodey** [morbac/xmltools#98]
Please see this thread for reference.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9426

I confirmed the problem exists with XMLTools 3.1.1.1 enabled, and so far several of us have tested with XMLTools disabled without problems.  The issue appears to be random - at least, we haven't seen any pattern so far.  I notice the issue most often when writing code, for what it's worth.

**Comment by morbac** [comment]
Thanks for your feedback. I'll try to find the root cause.

The only function of plugin which plays with undo is the "Tag auto-close" one (menu Plugins > XML Tools > Tag auto-close). An undo sequence is created in this case to allow user to remove the newly added closing tag in a single undo command. Maybe something goes wrong with that part and the undo sequence is never ended (which could explain the behaviour you described).

It would maybe help if you can tell if the option was enabled or disabled when you encountered the issue. It might be useful to try using NPP with XMLTools enabled, but with "Tag auto-close" disabled and see if problem still occurres.

Regards

**Comment by rkodey** [comment]
Sure - happy to try to help out.
Tag auto-close was NOT enabled when encountering the problem.  My current settings are captured in screenshots below.
For what it's worth, most of my work is in JavaScript, some HTML, and almost never pure XML.

I'm happy to try messing around with settings - although triggering the problem is random at best.  But it seems to strike right at the wrong time editing some important block of code!!  :)

![image](https://user-images.githubusercontent.com/433097/114815996-5360dc00-9d85-11eb-9f36-ae2f7faefa20.png)
![image](https://user-images.githubusercontent.com/433097/114815899-2ad8e200-9d85-11eb-8bb0-c5b1fb82701c.png)

**Comment by rkodey** [comment]
Just as an additional test, I un-checked the 3 settings above, and eventually provoked the same problem.
For my next test, I have removed all of the keyboard shortcuts, to eliminate the possibility that I'm triggering an XML function without realizing it.  As best I can tell, the problem happens without using any XML related functions.  Weird.

**Comment by rkodey** [comment]
Removing keyboard shortcuts did not prevent the problem, FYI.
I'm going to disable XMLTools again, just to verify the problem goes away again.

**Comment by rkodey** [comment]
It appears this was a false-positive.  The NPP error has come back without XML Tools installed.
Sorry for the inconvenience.
